### ISSUE TITLE
Tracking issue: Porting the MINPACK implementation

### ISSUE THREAD

**Issue by jannschu** [rust-cv/levenberg-marquardt#6]
My initial implementation has progressed. The code can be found [on this branch](https://github.com/jannschu/levenberg-marquardt/tree/minpack-rewrite).

# State

- [x] Implementation of pivoted QR factorization
  - [x] Generate test cases from reference implementation
- [x] Efficient linear least-squares solver for systems with diagonal updates
  - [x] Generate test cases from reference implementation
- [x] Implement Newton based iteration for finding lambda (`LMPAR` routine in MINPACK)
  - [x] Generate test cases from reference implementation
- [x] Add documentation with overview and full usage example (uses [KaTeX](https://katex.org/)).
- [x] Line fitting integration test was reparametrized to use an angle for the normal. This fixed an issue with the Jacobian being wrong.
- [x] Return statistics, as in #3.
- [x] Improve the API, as in #4.
- [x] Provide numerical differentiation helper (useful for unit tests, also in user code)
  - [x] Documentation with usage example for this
- [x] Implement high-level LM algorithm (trust region algorithm) exactly as in MINPACK
  - [x] Split this up into smaller pieces to ease unit tests and improve readability.
  - [x] Generate test cases from reference implementation.
  - [x] Check with classic test functions, see [here](https://github.com/pkgw/pwkit/blob/master/pwkit/lmmin.py) or [here](https://sci-hub.tw/10.1007/BFb0067700).
- [x] Adjust README.

All test cases, including the line fitting test case,  run in 2 seconds on my laptop.

The new implementation has all the termination criteria from MINPACK. 

I will open a pull request once everythings done.

**Comment by vadixidav** [comment]
This is really awesome, and I appreciate the work you are putting in here! This will put us in a good position to have fast and robust camera tracking.

**Comment by jannschu** [comment]
Just a quick update on the state of this: I added almost all the test functions I wanted and after some intensive debugging everything indicates now that the implementation produces the _same floating point output_ as MINPACK. Some of these changes are behind are feature flag, though. The test cases now pass with the real output of MINPACK which is a bit crazy/unnecessary to be honest, but I was curious.

In the process I also noticed that the finite difference scheme I implemented was below what's possible. I tried three different adaptive finite difference algorithms, one was ported from ALGOL 60 which was no fun. I will now try one final algorithm which from the first tests seems promising and then pick the best one.
